#!/usr/bin/env python3
"""Generate README.md and databricks.yml for the classic Python templates.

Inputs per template: manifest.yaml (name, description, resources, OBO scopes),
app.yaml (command, env wiring), and the tracked file list.

A README.md without the GENERATED marker is hand-written and left alone.
databricks.yml is always regenerated.

Usage: uv run --with pyyaml python .scripts/generate-classic-docs.py
"""

import subprocess
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))
from templates import CLASSIC_TEMPLATES  # noqa: E402

MARKER = "<!-- GENERATED by .scripts/generate-classic-docs.py from manifest.yaml + app.yaml. Edit the generator, not this file. -->"
MAX_APP_NAME = 26  # Databricks Apps limit, leaving room for a dev- prefix

FRAMEWORKS = {
    "streamlit": "Streamlit",
    "e2e": "Streamlit",
    "dash": "Dash",
    "gradio": "Gradio",
    "shiny": "Shiny for Python",
    "flask": "Flask",
    "nodejs": "React + FastAPI",
}

FILE_ROLES = {
    "app.py": "UI and app logic: start here",
    "app.yaml": "Runtime command and env vars wired from resources",
    "databricks.yml": "Bundle definition for CLI / CI deploys",
    "manifest.yaml": "Template metadata shown in the Databricks UI",
    "requirements.txt": "Python dependencies installed on deploy",
    "model_serving_utils.py": "Client for the serving endpoint",
    "messages.py": "Chat message types",
    "DatabricksChatbot.py": "Chat UI component",
    "templates/index.html": "HTML template",
    "backend/main.py": "FastAPI backend (serves the built frontend + `/api`)",
    "frontend/src/App.tsx": "React UI",
    "package.json": "Frontend build (`npm run build` runs on deploy)",
}

# Per resource type: bundle variables (name -> description) and the bundle resource body.
RESOURCE_TYPES = {
    "sql_warehouse_spec": {
        "label": "SQL warehouse",
        "vars": {"sql_warehouse_id": "SQL warehouse ID (`databricks warehouses list`)"},
        "bundle": lambda p: {"sql_warehouse": {"id": "${var.sql_warehouse_id}", "permission": p}},
        "local": "export DATABRICKS_WAREHOUSE_ID=<warehouse-id>   # databricks warehouses list",
    },
    "serving_endpoint_spec": {
        "label": "Model Serving endpoint",
        "vars": {"serving_endpoint_name": "Serving endpoint name (`databricks serving-endpoints list`)"},
        "bundle": lambda p: {"serving_endpoint": {"name": "${var.serving_endpoint_name}", "permission": p}},
        "local": "export SERVING_ENDPOINT=<endpoint-name>   # e.g. databricks-meta-llama-3-3-70b-instruct",
    },
    "database_spec": {
        "label": "Lakebase Provisioned database",
        "vars": {
            "database_instance_name": "Lakebase Provisioned instance name (`databricks database list-database-instances`)",
            "database_name": "Postgres database name inside the instance",
        },
        "defaults": {"database_name": "databricks_postgres"},
        "bundle": lambda p: {
            "database": {
                "instance_name": "${var.database_instance_name}",
                "database_name": "${var.database_name}",
                "permission": p,
            }
        },
        "local": (
            "# Connection details are on the instance's Connect tab in the Lakebase UI\n"
            "export PGHOST=<instance-host> PGPORT=5432 PGDATABASE=databricks_postgres\n"
            "export PGUSER=<your-databricks-username> PGSSLMODE=require PGAPPNAME=local"
        ),
    },
    "postgres_spec": {
        "label": "Lakebase Autoscaling database",
        "vars": {
            "postgres_branch": "Lakebase branch resource name, e.g. projects/<project>/branches/production (`databricks postgres list-branches projects/<project>`)",
            "postgres_database": "Lakebase database resource name, e.g. projects/<project>/branches/production/databases/<db> (`databricks postgres list-databases <branch>`)",
        },
        "bundle": lambda p: {
            "postgres": {"branch": "${var.postgres_branch}", "database": "${var.postgres_database}", "permission": p}
        },
        "local": (
            "# Connection details are on the branch's Connect tab in the Lakebase UI\n"
            "export PGENDPOINT=projects/<project>/branches/<branch>/endpoints/<endpoint>\n"
            "export PGHOST=<endpoint-host> PGPORT=5432 PGDATABASE=databricks_postgres\n"
            "export PGUSER=<your-databricks-username> PGSSLMODE=require PGAPPNAME=local"
        ),
    },
    "job_spec": {
        "label": "Lakeflow Job",
        "vars": {"job_id": "Job ID (`databricks jobs list`)"},
        "bundle": lambda p: {"job": {"id": "${var.job_id}", "permission": p}},
        "local": "export DATABRICKS_JOB_ID=<job-id>   # databricks jobs list",
    },
    # uc_securable_spec is keyed by securable type, see load().
    "uc_securable_spec:VOLUME": {
        "label": "Unity Catalog volume",
        "vars": {"volume_full_name": "Volume full name: <catalog>.<schema>.<volume>"},
        "bundle": lambda p: {
            "uc_securable": {
                "securable_full_name": "${var.volume_full_name}",
                "securable_type": "VOLUME",
                "permission": p,
            }
        },
        "local": "export DATABRICKS_VOLUME_PATH=/Volumes/<catalog>/<schema>/<volume>",
    },
    "uc_securable_spec:TABLE": {
        "label": "Vector Search index",
        "vars": {"vector_search_index": "Vector Search index full name: <catalog>.<schema>.<index>"},
        "bundle": lambda p: {
            "uc_securable": {
                "securable_full_name": "${var.vector_search_index}",
                "securable_type": "TABLE",
                "permission": p,
            }
        },
        "local": "export VECTOR_SEARCH_INDEX=<catalog>.<schema>.<index>",
    },
}

# Extra README section for templates that need setup beyond declaring resources.
SETUP_NOTES = {
    "streamlit-jobs-app": [
        "- Pick any job; the app reads its job parameters and shows them as inputs.",
        "- Task output shown per task: notebook tasks return the value passed to",
        "  `dbutils.notebook.exit(\"...\")`; other task types show logs or errors.",
        "- The runs table refreshes every 5 seconds (`st.fragment(run_every=...)`).",
    ],
    "streamlit-files-app": [
        "- All paths are resolved inside the volume; names like `../x` are rejected.",
        "- Uploads overwrite files with the same name. Deletes require a confirmation tick.",
        "- Streamlit's default upload limit is 200 MB per file (`server.maxUploadSize`).",
    ],
    "streamlit-vector-search-app": [
        "- Text queries need a **Delta Sync index with managed embeddings**. For self-managed",
        "  embeddings, compute the query vector yourself and pass `query_vector` instead.",
        "- Returned columns default to the primary key + the embedding source column;",
        "  set `VECTOR_SEARCH_COLUMNS` in `app.yaml` to choose others.",
    ],
    "streamlit-synced-table-app": [
        "1. Create a synced table from a Unity Catalog table into the Lakebase database",
        "   (*Catalog Explorer → table → Create → Synced table*).",
        "2. Set `SYNCED_TABLE` (`<postgres-schema>.<table>`) and `SEARCH_COLUMN` in `app.yaml`.",
        "3. After the first deploy, let the app's service principal read the table. In the",
        "   Lakebase SQL editor, as the table owner (the role name is the app's service",
        "   principal client ID, shown on the app's *Authorization* tab):",
        "   ```sql",
        "   GRANT USAGE ON SCHEMA <schema> TO \"<app-service-principal-client-id>\";",
        "   GRANT SELECT ON <schema>.<table> TO \"<app-service-principal-client-id>\";",
        "   ```",
        "4. For fast prefix search on large tables, add an index:",
        "   `CREATE INDEX ON <schema>.<table> (<column> text_pattern_ops);`",
        "",
        "Use this pattern for typeahead and lookups by key. For dashboards and aggregations,",
        "query the SQL warehouse instead (see `streamlit-data-app`).",
    ],
    "streamlit-group-access-app": [
        "- User authorization must be enabled for apps in the workspace (ask an admin if deploy",
        "  fails with `user token passthrough not enabled`).",
        "- Set `ADMIN_GROUP` in `app.yaml` to the workspace group that sees the admin section.",
        "- Hiding UI is not access control: enforce the same rule wherever data is read or",
        "  written (Unity Catalog grants, or the `is_admin` check in your handlers).",
        "- Streamlit reads request headers once per session, so the user token can go stale",
        "  on a long-open tab; reloading the page refreshes it.",
    ],
}


def load(template: str) -> dict:
    d = REPO_ROOT / template
    manifest = yaml.safe_load((d / "manifest.yaml").read_text())
    app = yaml.safe_load((d / "app.yaml").read_text())
    env_by_resource = {e["valueFrom"]: e["name"] for e in app.get("env", []) if "valueFrom" in e}
    resources = []
    for spec in manifest.get("resource_specs", []):
        kind = next(k for k in spec if k.endswith("_spec"))
        permission = spec[kind]["permission"]
        if kind == "uc_securable_spec":
            kind += ":" + spec[kind]["securable_type"]
        resources.append(
            {
                "name": spec["name"],
                "kind": kind,
                "permission": permission,
                "description": spec.get("description", ""),
                "env": env_by_resource.get(spec["name"]),
            }
        )
    files = subprocess.check_output(["git", "ls-files", "--cached", "--others", "--exclude-standard"], cwd=d, text=True).split()
    return {
        "template": template,
        "framework": FRAMEWORKS[template.split("-")[0]],
        "manifest": manifest,
        "command": " ".join(app["command"]),
        "resources": resources,
        "scopes": manifest.get("user_api_scopes", []),
        "files": [f for f in files if not f.startswith(".")],
    }


def app_name(template: str) -> str:
    name = template.replace("-app", "")
    assert len(name) <= MAX_APP_NAME, f"{name} exceeds {MAX_APP_NAME} chars"
    return name


def render_bundle(t: dict) -> str:
    variables, defaults = {}, {}
    for r in t["resources"]:
        rt = RESOURCE_TYPES[r["kind"]]
        variables.update(rt["vars"])
        defaults.update(rt.get("defaults", {}))
    app = {
        "name": app_name(t["template"]),
        "description": t["manifest"]["description"],
        "source_code_path": "./",
    }
    if t["scopes"]:
        app["user_api_scopes"] = t["scopes"]
    if t["resources"]:
        app["resources"] = [
            {"name": r["name"], **RESOURCE_TYPES[r["kind"]]["bundle"](r["permission"])} for r in t["resources"]
        ]
    bundle = {"bundle": {"name": t["template"]}}
    if variables:
        bundle["variables"] = {
            k: {"description": v, **({"default": defaults[k]} if k in defaults else {})} for k, v in variables.items()
        }
    bundle["resources"] = {"apps": {"app": app}}
    bundle["targets"] = {
        "dev": {"mode": "development", "default": True},
        "prod": {"mode": "production"},
    }
    header = (
        "# Generated by .scripts/generate-classic-docs.py. Edit the generator, not this file.\n"
        "# Deploy:  databricks bundle deploy -t dev"
        + "".join(f" --var {k}=<...>" for k in variables if k not in defaults)
        + "\n#          databricks bundle run app -t dev\n"
    )
    return header + yaml.safe_dump(bundle, sort_keys=False, width=1000)


def render_readme(t: dict) -> str:
    m, res = t["manifest"], t["resources"]
    obo = bool(t["scopes"])
    out = [MARKER, "", f"# {t['framework']}: {m['name']}", "", m["description"], ""]

    out += ["| | |", "|---|---|", f"| Framework | {t['framework']} |"]
    auth = f"On-behalf-of user (scopes: {', '.join(f'`{s}`' for s in t['scopes'])})" if obo else "App service principal"
    out += [f"| Runs as | {auth} |"]
    out += [f"| Resources | {', '.join(RESOURCE_TYPES[r['kind']]['label'] for r in res) or 'None'} |", ""]

    if res:
        out += ["## Resources", "", "| Resource key | Type | Permission | Exposed to the app as |", "|---|---|---|---|"]
        for r in res:
            env = f"`{r['env']}`" if r["env"] else ""
            if r["kind"] in ("database_spec", "postgres_spec"):
                env = ", ".join(filter(None, [env, "`PGHOST`, `PGDATABASE`, `PGUSER`, ... (injected)"]))
            out += [f"| `{r['name']}` | {RESOURCE_TYPES[r['kind']]['label']} | `{r['permission']}` | {env} |"]
        out += [""] + [f"- **`{r['name']}`**: {r['description']}" for r in res] + [""]

    if t["template"] in SETUP_NOTES:
        out += ["## Setup", "", *SETUP_NOTES[t["template"]], ""]

    out += ["## How it authenticates", ""]
    if obo:
        out += [
            "Queries run **as the signed-in user**. Databricks forwards the user's token in the",
            "`X-Forwarded-Access-Token` header, so Unity Catalog permissions are enforced per user.",
            "",
            "- The app needs the user API scopes above (declared in `databricks.yml` / set in the UI).",
            "- A workspace admin may need to enable user authorization for apps.",
            "- Locally there is no forwarded header, so the on-behalf-of path only works once deployed.",
        ]
    else:
        out += [
            "The app runs as its own **service principal**. Databricks injects its OAuth credentials",
            "(`DATABRICKS_CLIENT_ID` / `DATABRICKS_CLIENT_SECRET`) and the SDK picks them up automatically.",
        ]
        if res:
            out += [
                "",
                "Declaring a resource grants the service principal the permission listed above on that resource.",
            ]
        if any(r["kind"] == "sql_warehouse_spec" for r in res):
            out += [
                "Table access is separate: grant the service principal (its ID is on the app's",
                "*Authorization* tab) access to the Unity Catalog tables it queries:",
                "",
                "```sql",
                "GRANT USE CATALOG ON CATALOG <catalog> TO `<app-service-principal-id>`;",
                "GRANT USE SCHEMA ON SCHEMA <catalog>.<schema> TO `<app-service-principal-id>`;",
                "GRANT SELECT ON TABLE <catalog>.<schema>.<table> TO `<app-service-principal-id>`;",
                "```",
            ]
        if t["template"].endswith(("-database-app", "-postgres-app")):
            out += ["On first start the app creates its own schema and `todos` table in the database."]
    out += [""]

    local_env = [RESOURCE_TYPES[r["kind"]]["local"] for r in res]
    is_node = "package.json" in t["files"]
    out += ["## Run locally", "", "```bash"]
    if res:
        out += ["databricks auth login --host <workspace-url> --profile <profile>", "export DATABRICKS_CONFIG_PROFILE=<profile>"]
        out += local_env
        out += [""]
    out += ["uv venv && source .venv/bin/activate", "uv pip install -r requirements.txt"]
    if is_node:
        out += ["npm install && npm run build"]
    out += [t["command"], "```", ""]

    deploy_vars = "".join(
        f" \\\n  --var {k}=<...>"
        for r in res
        for k in RESOURCE_TYPES[r["kind"]]["vars"]
        if k not in RESOURCE_TYPES[r["kind"]].get("defaults", {})
    )
    out += [
        "## Deploy",
        "",
        "**From the UI:** *Compute → Apps → Create app → pick this template*, then select the resources.",
        "",
        "**With a bundle (CLI / CI):**",
        "",
        "```bash",
        f"databricks bundle deploy -t dev --profile <profile>{deploy_vars}",
        "databricks bundle run app -t dev --profile <profile>",
        "databricks apps logs <app-name> --profile <profile>   # needs OAuth, not a PAT",
        "```",
        "",
        "Use `-t prod` for a production deploy. Run `databricks bundle summary -t dev` to see the deployed app name and URL.",
        "",
        "## Files",
        "",
        "| File | Purpose |",
        "|---|---|",
    ]
    files = dict.fromkeys([*t["files"], "databricks.yml"])  # ordered, deduped
    out += [f"| `{f}` | {FILE_ROLES[f]} |" for f in files if f in FILE_ROLES]
    out += [
        "",
        "## Testing",
        "",
        "`.scripts/classic-app-tests/` checks that `requirements.txt` resolves, that the app boots (when it",
        "can start without a workspace), and that `databricks.yml` matches the bundle schema.",
        "",
        "## More",
        "",
        "[Authentication](../docs/authentication.md) · [Resources and permissions](../docs/resources-and-permissions.md) · "
        "[Production checklist](../docs/production-checklist.md) · [Troubleshooting](../docs/troubleshooting.md)",
        "",
    ]
    return "\n".join(out)


def main() -> None:
    for template in CLASSIC_TEMPLATES:
        t = load(template)
        d = REPO_ROOT / template
        (d / "databricks.yml").write_text(render_bundle(t))
        readme = d / "README.md"
        if readme.exists() and MARKER not in readme.read_text():
            print(f"{template}: databricks.yml (README.md is hand-written, kept)")
            continue
        readme.write_text(render_readme(t))
        print(f"{template}: databricks.yml, README.md")


if __name__ == "__main__":
    main()
